[tool.poetry]
name = "researchpy"
version = "0.1.0"
description = "Quickly manage your research projects"
authors = ["Vivek Rai <vivekrai@umich.edu>"]

[tool.poetry.dependencies]
python = "^3.7"
toml = "^0.10.0"
snakemake = {version = "^5.8.2", optional = true}
click = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[tool.poetry.scripts]
researchpy = 'researchpy.cli:cli'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
